"use client";
import AppProvider from "@/context/AppProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>AUSDC - Token Dashboard</title>
        <meta
          name="description"
          content="AUSD Token Dashboard allows you to track the transaction happening
          over AUSDC token on Base goerli network"
        />
        <meta name="author" content="Abhishek Upadhyay" />
      </head>
      <body className={roboto.className}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
