"use client";
import AppProvider from "@/context/AppProvider";
import { usePathname } from "next/navigation";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const navItems = [
  { name: "Transactions", href: "/" },
  { name: "Holders", href: "/holders" },
  { name: "Minters", href: "/minters" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  const isSelectedPath = (route: string) => pathname === route;

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="sidebar">
          <p className="brand">Token Dashboard</p>
          <ul className="menus">
            {navItems.map((nav) => (
              <li
                key={nav.name}
                className={`menu ${isSelectedPath(nav.href) ? "selected" : ""}`}
              >
                <Link href={nav.href}>{nav.name}</Link>
              </li>
            ))}
          </ul>
        </div>
        <div className="page-container">
          <AppProvider>{children}</AppProvider>
        </div>
      </body>
    </html>
  );
}
